services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    working_dir: /app/app
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - type: volume
        source: frontend_node_modules
        target: /app/node_modules
    command: npm run dev

volumes:
  db_data:
  frontend_node_modules: